name: Python CI for Pytest

# Déclenchement du workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.3'

      # Étape 3 : Mettre en cache les packages Python
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          # Chemin vers le cache des packages pip
          path: ~/.cache/pip
          # Clé unique basée sur le système d'exploitation et le hash du fichier requirements.txt
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          # Clés de restauration au cas où la clé principale ne serait pas trouvée
          restore-keys: |
            ${{ runner.os }}-pip-

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      # Étape 5 : Exécuter les tests avec pytest
      - name: Run tests
        run: pytest --cov=scripts --cov=src --cov-report term-missing tests/
