name: Python CI for Pytest

# Déclenchement du workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.3'

      

      # Étape 3 : Installer les dépendances
      - name: Install cache
        uses: actions/cache@v2
        id: cache-venv  # name for referring later
        with:
          path: ./.venv/  # what we cache: the virtualenv
          # The cache key depends on requirements.txt
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      # Build a virtualenv, but only if it doesn't already exist
      - run: python -m venv ./.venv && . ./.venv/bin/activate && 
           pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
    
      # Étape 5 : Exécuter les tests avec pytest
      - name: Run tests
        run: . ./.venv/bin/activate && pytest --cov=scripts --cov=src --cov-report term-missing tests/
