name: Python CI for Pytest

# Déclenchement du workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.3'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      # Étape 5 : Exécuter les tests avec pytest
      - name: Run tests
        run: pytest --cov=scripts --cov=src --cov-report term-missing tests/
