[theme]
primaryColor = "#e76d00"  # Couleur principale 
backgroundColor = "#ebcdac" 
secondaryBackgroundColor = "#a1815b"  
textColor = "#55381f"  # Couleur du texte
font = "sans serif"  # Police globale

[server]
runOnSave = true